{
  "hash": "17ce90f2a7a096c58cd925909210ff4a",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Lab 3. Specialized Chart Types\"\nsubtitle: \"PUBH 6199: Visualizing Data with R, Summer 2026\"\ndate: June 4, 2026\nauthor: Xindi (Cindy) Hu, ScD\nformat: \n  revealjs:\n    pdf: true\n    slide-number: true\n    chalkboard: \n      buttons: false\n    preview-links: auto\n    logo: images/logo-square.png\n    css: style.css\n    footer: 'PUBH 6199: Visualizing Data with R'\nresources:\n  - images/\n---\n\n\n::: {.cell}\n\n:::\n\n\n## Outline for today {.smaller}\n\n- **Introducing the datasets**\n\n- Review faceted plots\n\n- Introduce radar charts, Sankey diagrams, and parallel coordinates plot\n\n- Dos and Don'ts when designing visualizations\n\n\n## Forest Fires Dataset {.smaller}\n\n:::{.column width=\"60%\"}\n\n- **Source**: UCI Machine Learning Repository  \n  [https://archive.ics.uci.edu/ml/datasets/forest+fires](https://archive.ics.uci.edu/ml/datasets/forest+fires)\n\n- **Context**: Collected from the Montesinho Natural Park in Portugal, this dataset captures weather conditions and fire activity over 200+ days. The task was to predict the burned area of forest fires based on meteorological and fire weather indices.\n\n- **Variables**:\n  - `month`, `day`: Temporal context\n  - `temp`, `RH`, `wind`, `rain`: Daily weather\n  - `FFMC`, `DMC`, `DC`, `ISI`: Fire weather indices\n  - `area`: Outcome of interest, burned area in hectares\n  \n:::\n\n::: {.column width=\"40%\"}\n![](images/fwi_structure.gif){width=100%}\n\n::: citation\n[Canadian Forest Fire Weather Index (FWI) System](https://cwfis.cfs.nrcan.gc.ca/background/summary/fwi)\n:::\n\n:::\n\n## Forest Fires Dataset {.smaller}\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nforest <- read_csv(\"https://archive.ics.uci.edu/ml/machine-learning-databases/forest-fires/forestfires.csv\")\nglimpse(forest)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 517\nColumns: 13\n$ X     <dbl> 7, 7, 7, 8, 8, 8, 8, 8, 8, 7, 7, 7, 6, 6, 6, 6, 5, 8, 6, 6, 6, 5…\n$ Y     <dbl> 5, 4, 4, 6, 6, 6, 6, 6, 6, 5, 5, 5, 5, 5, 5, 5, 5, 5, 4, 4, 4, 4…\n$ month <chr> \"mar\", \"oct\", \"oct\", \"mar\", \"mar\", \"aug\", \"aug\", \"aug\", \"sep\", \"…\n$ day   <chr> \"fri\", \"tue\", \"sat\", \"fri\", \"sun\", \"sun\", \"mon\", \"mon\", \"tue\", \"…\n$ FFMC  <dbl> 86.2, 90.6, 90.6, 91.7, 89.3, 92.3, 92.3, 91.5, 91.0, 92.5, 92.5…\n$ DMC   <dbl> 26.2, 35.4, 43.7, 33.3, 51.3, 85.3, 88.9, 145.4, 129.5, 88.0, 88…\n$ DC    <dbl> 94.3, 669.1, 686.9, 77.5, 102.2, 488.0, 495.6, 608.2, 692.6, 698…\n$ ISI   <dbl> 5.1, 6.7, 6.7, 9.0, 9.6, 14.7, 8.5, 10.7, 7.0, 7.1, 7.1, 22.6, 0…\n$ temp  <dbl> 8.2, 18.0, 14.6, 8.3, 11.4, 22.2, 24.1, 8.0, 13.1, 22.8, 17.8, 1…\n$ RH    <dbl> 51, 33, 33, 97, 99, 29, 27, 86, 63, 40, 51, 38, 72, 42, 21, 44, …\n$ wind  <dbl> 6.7, 0.9, 1.3, 4.0, 1.8, 5.4, 3.1, 2.2, 5.4, 4.0, 7.2, 4.0, 6.7,…\n$ rain  <dbl> 0.0, 0.0, 0.0, 0.2, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,…\n$ area  <dbl> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0…\n```\n\n\n:::\n:::\n\n\n## Adult Income Dataset {.smaller}\n\n- **Source**: UCI Machine Learning Repository  \n  [https://archive.ics.uci.edu/ml/datasets/adult](https://archive.ics.uci.edu/ml/datasets/adult)\n\n- **Context**: Extracted from 1994 U.S. Census data to predict whether an individual's income exceeds \\$50K/year.\n\n- **Variables**:\n  - Demographics: `age`, `sex`, `race`, `education`, `marital-status`\n  - Employment: `workclass`, `occupation`, `hours-per-week`\n  - Target: `income` (>50K or ≤50K)\n\n## Adult Income Dataset {.smaller}\n\n\n::: {.cell}\n\n```{.r .cell-code}\nadult <- read_csv(\"https://archive.ics.uci.edu/ml/machine-learning-databases/adult/adult.data\",\n                  col_names = c(\"age\", \"workclass\", \"fnlwgt\", \"education\", \"education_num\",\n                                \"marital_status\", \"occupation\", \"relationship\", \"race\", \"sex\",\n                                \"capital_gain\", \"capital_loss\", \"hours_per_week\", \"native_country\", \"income\"))\nglimpse(adult)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 32,561\nColumns: 15\n$ age            <dbl> 39, 50, 38, 53, 28, 37, 49, 52, 31, 42, 37, 30, 23, 32,…\n$ workclass      <chr> \"State-gov\", \"Self-emp-not-inc\", \"Private\", \"Private\", …\n$ fnlwgt         <dbl> 77516, 83311, 215646, 234721, 338409, 284582, 160187, 2…\n$ education      <chr> \"Bachelors\", \"Bachelors\", \"HS-grad\", \"11th\", \"Bachelors…\n$ education_num  <dbl> 13, 13, 9, 7, 13, 14, 5, 9, 14, 13, 10, 13, 13, 12, 11,…\n$ marital_status <chr> \"Never-married\", \"Married-civ-spouse\", \"Divorced\", \"Mar…\n$ occupation     <chr> \"Adm-clerical\", \"Exec-managerial\", \"Handlers-cleaners\",…\n$ relationship   <chr> \"Not-in-family\", \"Husband\", \"Not-in-family\", \"Husband\",…\n$ race           <chr> \"White\", \"White\", \"White\", \"Black\", \"Black\", \"White\", \"…\n$ sex            <chr> \"Male\", \"Male\", \"Male\", \"Male\", \"Female\", \"Female\", \"Fe…\n$ capital_gain   <dbl> 2174, 0, 0, 0, 0, 0, 0, 0, 14084, 5178, 0, 0, 0, 0, 0, …\n$ capital_loss   <dbl> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0…\n$ hours_per_week <dbl> 40, 13, 40, 40, 40, 40, 16, 45, 50, 40, 80, 40, 30, 50,…\n$ native_country <chr> \"United-States\", \"United-States\", \"United-States\", \"Uni…\n$ income         <chr> \"<=50K\", \"<=50K\", \"<=50K\", \"<=50K\", \"<=50K\", \"<=50K\", \"…\n```\n\n\n:::\n:::\n\n\n## Outline for today {.smaller}\n\n- Introducing the datasets\n\n- **Review faceted plots**\n\n- Introduce radar charts, Sankey diagrams, and parallel coordinates plot\n\n- Dos and Don'ts when designing visualizations\n\n## Review: Faceted Plots {.smaller}\n\n>In previous lecture/labs, we learned about faceted plots, which allow us to create multiple subplots based on a categorical variable. This is particularly useful for comparing distributions or trends across different groups.\n\n::: {.column width=\"50%\"}\n\n::: {.cell}\n\n```{.r .cell-code}\n# Faceted scatter plot: Temp vs Wind, faceted by month\nggplot(forest, aes(x = temp, y = wind)) +\n  geom_point(alpha = 0.6, color = \"firebrick\") +\n  facet_wrap(~ month, ncol = 4) +\n  labs(title = \"Temperature vs Wind Speed by Month\",\n       x = \"Temperature (°C)\",\n       y = \"Wind Speed (km/h)\") +\n  theme_minimal()\n```\n:::\n\n:::\n\n::: {.column width=\"50%\"}\n\n::: {.cell}\n::: {.cell-output-display}\n![](index_files/figure-revealjs/unnamed-chunk-4-1.png){width=384}\n:::\n:::\n\n:::\n\n\n## Review: Faceted Plots {.smaller}\n\n>Optional: convert month to ordered factor for nicer facet layout\n\n::: {.column width=\"50%\"}\n\n\n::: {.cell}\n\n```{.r .cell-code  code-line-numbers=\"1-3\"}\nforest <- forest %>%\n  mutate(month = factor(month, levels = c(\"jan\", \"feb\", \"mar\", \"apr\", \"may\", \"jun\",\n                                          \"jul\", \"aug\", \"sep\", \"oct\", \"nov\", \"dec\")))\n\nggplot(forest, aes(x = temp, y = wind)) +\n  geom_point(alpha = 0.6, color = \"firebrick\") +\n  facet_wrap(~ month, ncol = 4) +\n  labs(title = \"Temperature vs Wind Speed by Month\",\n       x = \"Temperature (°C)\",\n       y = \"Wind Speed (km/h)\") +\n  theme_minimal()\n```\n:::\n\n\n:::\n\n::: {.column width=\"50%\"}\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](index_files/figure-revealjs/unnamed-chunk-6-1.png){width=384}\n:::\n:::\n\n\n:::\n\n## Facet plots by combining two variables {.smaller-title}\n\n::: .smaller\nDoes dry air (low RH) change the relationship between wind and temperature across seasons? We use `facet_grid()` to create a grid of plots, where each row represents a season and each column represents a relative humidity level.\n:::\n\n::: {.column width=\"50%\" style=\"font-size: 0.8em;\"}\n\n\n::: {.cell}\n\n```{.r .cell-code  code-line-numbers=\"19\"}\nforest <- forest %>%\n  mutate(\n    month = tolower(month),\n    season = case_when(\n      month %in% c(\"dec\", \"jan\", \"feb\") ~ \"Winter\",\n      month %in% c(\"mar\", \"apr\", \"may\") ~ \"Spring\",\n      month %in% c(\"jun\", \"jul\", \"aug\") ~ \"Summer\",\n      month %in% c(\"sep\", \"oct\", \"nov\") ~ \"Fall\",\n      TRUE ~ \"Unknown\"\n    ),\n    RH_level = if_else(RH >= median(RH, na.rm = TRUE), \"High RH\", \"Low RH\"),\n    season = factor(season, levels = c(\"Spring\", \"Summer\", \"Fall\", \"Winter\")),\n    RH_level = factor(RH_level, levels = c(\"Low RH\", \"High RH\"))\n  )\n\n# Faceted scatter plot: temp vs wind by season and RH level\nggplot(forest, aes(x = temp, y = wind)) +\n  geom_point(alpha = 0.6, color = \"darkorange\") +\n  facet_grid(rows = vars(season), cols = vars(RH_level)) +\n  labs(\n    title = \"Temperature vs Wind Speed\\nby Season and Relative Humidity Level\",\n    x = \"Temperature (°C)\",\n    y = \"Wind Speed (km/h)\"\n  ) +\n  theme_minimal(base_size = 11)\n```\n:::\n\n\n\n:::\n\n::: {.column width=\"50%\"}\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](index_files/figure-revealjs/unnamed-chunk-8-1.png){width=480}\n:::\n:::\n\n\n:::\n\n## Use fixed vs free scales {.smaller-title}\n\n::: .smaller\nUsing fixed scales can help in comparing values across different facets, while free scales allow each facet to have its own scale, which can be useful when the data varies widely between groups.\n:::\n\n::: {.column width=\"50%\"}\n\n\n::: {.cell}\n\n```{.r .cell-code  code-line-numbers=\"7\"}\nforest <- forest %>%\n  mutate(month = factor(month, levels = c(\"jan\", \"feb\", \"mar\", \"apr\", \"may\", \"jun\",\n                                          \"jul\", \"aug\", \"sep\", \"oct\", \"nov\", \"dec\")))\n\nggplot(forest, aes(x = temp, y = wind)) +\n  geom_point(alpha = 0.6, color = \"firebrick\") +\n  facet_wrap(~ month, ncol = 4, scales = \"free_y\") +\n  labs(title = \"Temperature vs Wind Speed by Month\",\n       x = \"Temperature (°C)\",\n       y = \"Wind Speed (km/h)\") +\n  theme_minimal()\n```\n:::\n\n:::\n\n\n::: {.column width=\"50%\"}\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](index_files/figure-revealjs/unnamed-chunk-10-1.png){width=480}\n:::\n:::\n\n\n:::\n\n##  {background=\"#033C5A\"}\n<br>\n<br>\n<br>\n\n<div class=\"page-center vertical-center\">\n<p class=\"custom-subtitle bottombr\">{{<fa bicycle title=\"let's get on the bike\" >}} Your turn, get on the bike! </p>\n<p class=\"caption-text\">*~ Head over to lab3 notebook! ~*</p>\n</div>\n\n## Outline for today {.smaller}\n\n- Introducing the datasets\n\n- Review faceted plots\n\n- **Introduce radar charts, Sankey diagrams, and parallel coordinates plot**\n\n- Dos and Don'ts when designing visualizations\n\n## What is a Radar Chart? {.smaller}\n\n- A radar chart (or spider chart) displays multivariate data on axes starting from the same point.\n- Good for comparing profiles across a few categories or groups.\n- Useful when variables are on the **same scale** or **normalized**.\n\n## Why Use a Radar Chart to explore the `forest` data? {.smaller}\n\n- Compare **weather profiles** for different fire conditions.\n- Visualize **relative intensity** of multiple variables at once (e.g., `temp`, `wind`, `RH`).\n- Spot patterns across fire size categories.\n\n## Step 1: Load and prepare the data {.smaller}\n\n> Forest Fires Dataset\nThis dataset contains 517 observations, each representing a single day of recorded weather conditions and fire activity in the Montesinho Natural Park in Portugal. Each observation includes meteorological variables such as temperature, relative humidity (RH), wind speed, and rainfall, as well as fire weather indices (e.g., FFMC, DMC) and the area burned in hectares. The data spans multiple months and is commonly used to study environmental drivers of wildfire risk.\n\n:::scroll-output\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 517\nColumns: 14\n$ X          <dbl> 7, 7, 7, 8, 8, 8, 8, 8, 8, 7, 7, 7, 6, 6, 6, 6, 5, 8, 6, 6,…\n$ Y          <dbl> 5, 4, 4, 6, 6, 6, 6, 6, 6, 5, 5, 5, 5, 5, 5, 5, 5, 5, 4, 4,…\n$ month      <chr> \"mar\", \"oct\", \"oct\", \"mar\", \"mar\", \"aug\", \"aug\", \"aug\", \"se…\n$ day        <chr> \"fri\", \"tue\", \"sat\", \"fri\", \"sun\", \"sun\", \"mon\", \"mon\", \"tu…\n$ FFMC       <dbl> 86.2, 90.6, 90.6, 91.7, 89.3, 92.3, 92.3, 91.5, 91.0, 92.5,…\n$ DMC        <dbl> 26.2, 35.4, 43.7, 33.3, 51.3, 85.3, 88.9, 145.4, 129.5, 88.…\n$ DC         <dbl> 94.3, 669.1, 686.9, 77.5, 102.2, 488.0, 495.6, 608.2, 692.6…\n$ ISI        <dbl> 5.1, 6.7, 6.7, 9.0, 9.6, 14.7, 8.5, 10.7, 7.0, 7.1, 7.1, 22…\n$ temp       <dbl> 8.2, 18.0, 14.6, 8.3, 11.4, 22.2, 24.1, 8.0, 13.1, 22.8, 17…\n$ RH         <dbl> 51, 33, 33, 97, 99, 29, 27, 86, 63, 40, 51, 38, 72, 42, 21,…\n$ wind       <dbl> 6.7, 0.9, 1.3, 4.0, 1.8, 5.4, 3.1, 2.2, 5.4, 4.0, 7.2, 4.0,…\n$ rain       <dbl> 0.0, 0.0, 0.0, 0.2, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,…\n$ area       <dbl> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,…\n$ area_group <chr> \"No fire\", \"No fire\", \"No fire\", \"No fire\", \"No fire\", \"No …\n```\n\n\n:::\n:::\n\n:::\n\n## Step 2: Summarize and normalize variables {.smaller}\n\n::: {.column width=\"50%\"}\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(scales)\nlibrary(fmsb)\n# Select and normalize variables\nradar_data <- forest %>%\n    group_by(area_group) %>%\n    summarise(\n        temp = mean(temp),\n        RH = mean(RH),\n        wind = mean(wind),\n        rain = mean(rain)\n    ) %>%\n    # normalize to [0, 1]\n    mutate(across(where(is.numeric), rescale))  \n\n# Convert to fmsb format\n# fmsb expects first two rows to be max and min\nradar_df <- radar_data %>%\n    tibble::column_to_rownames(\"area_group\") %>%\n    as.data.frame()\n\n# fmsb expects first two rows: max then min\nmax_row <- rep(1, ncol(radar_df))\nmin_row <- rep(0, ncol(radar_df))\nradar_df <- rbind(max = max_row, min = min_row, radar_df)\n\nprint(radar_df)\n```\n:::\n\n\n:::\n\n::: {.column width=\"50%\"}\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n                 temp        RH      wind      rain\nmax         1.0000000 1.0000000 1.0000000 1.0000000\nmin         0.0000000 0.0000000 0.0000000 0.0000000\nLarge fire  0.2189738 0.0000000 1.0000000 1.0000000\nMedium fire 0.2379999 0.6826801 0.2434875 0.1404139\nNo fire     0.0000000 1.0000000 0.0000000 0.2043269\nSmall fire  1.0000000 0.4812876 0.2399755 0.0000000\n```\n\n\n:::\n:::\n\n\n:::\n\n## Step 3: Plot the Radar Chart {.smaller}\n\n::: {.column width=\"50%\"}\n\n\n::: {.cell}\n\n```{.r .cell-code}\nradarchart(radar_df,\n           axistype = 1,\n           pcol = c(\"red\", \"orange\", \"grey\", \"darkgreen\"),\n           plwd = 2,\n           plty = 1,\n           cglcol = \"grey\",\n           cglty = 1,\n           axislabcol = \"black\",\n           caxislabels = seq(0, 1, 0.2),\n           title = \"Weather Profiles by Fire Size\")\n\nlegend(\"bottomright\", \n       legend = rownames(radar_df[-c(1,2),]), \n       col = c(\"red\", \"orange\", \"grey\", \"darkgreen\"), \n       lty = 1, lwd = 2, bty = \"n\")\n```\n:::\n\n\n:::\n\n::: {.column width=\"50%\"}\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](index_files/figure-revealjs/unnamed-chunk-15-1.png){width=480}\n:::\n:::\n\n\n:::\n\n## Make radar chart with `{ggradar}` {.smaller}\n\nOnce you have `radar_data` prepared, you can use the `ggradar` package to create a more polished radar chart.\n\n::: {.column width=\"50%\"}\n\n\n::: {.cell}\n\n```{.r .cell-code}\nremotes::install_github(\"ricardo-bion/ggradar\")\nlibrary(ggradar)\nggradar(radar_data,\n        grid.min = 0, grid.mid = 0.5, grid.max = 1,\n        group.line.width = 1.2,\n        group.colours = c('red', 'orange', 'grey', 'darkgreen'),\n        group.point.size = 3,\n        font.radar = \"Arial\",\n        values.radar = c(\"0\", \"0.5\", \"1\"),\n        background.circle.colour = \"transparent\",\n        legend.position = \"bottom\") +\n    ggtitle(\"Weather Profiles by Fire Size\") +\n    theme(\n        legend.text = element_text(size = 11),\n        legend.key.width = unit(0.5, \"cm\")\n    )\n```\n:::\n\n\n:::\n\n::: {.column width=\"50%\"}\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](index_files/figure-revealjs/unnamed-chunk-17-1.png){width=432}\n:::\n:::\n\n\n:::\n\n## What is a Sankey diagram? {.smaller}\n\n- A **Sankey diagram** visualizes flows between categories.\n- The width of each flow is proportional to the count or magnitude.\n- Great for showing step-wise processes, transitions, or categorical relationships.\n\n\n## Why Use a Sankey Diagram to explore the `adult` data? {.smaller}\n- Visualize **income distribution** across multiple categorical variables.\n- Visualize **distributional flows** like:\n  - Education → Occupation → Income\n  - Gender → Workclass → Income\n\n## Step 1: Load and Prepare the Data {.smaller}\n\n> Adult Income Dataset\nThis dataset contains 32,561 observations, each representing a single adult individual from the 1994 U.S. Census database. Each observation includes demographic and employment-related variables such as age, sex, education, occupation, and work hours, as well as an income label indicating whether the person earns more or less than $50,000 per year. The dataset is commonly used to study social and economic patterns, and to explore factors associated with income inequality.\n\n:::scroll-output\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Keep only relevant columns\nadult_sankey <- adult %>%\n  select(sex, education, occupation, income) %>%\n  filter(complete.cases(.))\n\nflow_data <- adult_sankey %>%\n  count(sex, education, occupation, income) %>%\n  ungroup()\n\nglimpse(flow_data)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 623\nColumns: 5\n$ sex        <chr> \"Female\", \"Female\", \"Female\", \"Female\", \"Female\", \"Female\",…\n$ education  <chr> \"10th\", \"10th\", \"10th\", \"10th\", \"10th\", \"10th\", \"10th\", \"10…\n$ occupation <chr> \"?\", \"Adm-clerical\", \"Craft-repair\", \"Craft-repair\", \"Exec-…\n$ income     <chr> \"<=50K\", \"<=50K\", \"<=50K\", \">50K\", \"<=50K\", \">50K\", \"<=50K\"…\n$ n          <int> 42, 22, 10, 1, 7, 1, 4, 8, 30, 107, 4, 4, 3, 45, 1, 1, 5, 6…\n```\n\n\n:::\n:::\n\n:::\n\n## Step 2: Summarize and plot with `{ggalluvial}` {.smaller}\n\n>3-axis Sankey diagrams can quickly become cluttered when categorical variables have too many levels\n\n::: {.column width=\"50%\"}\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(ggalluvial)\nlibrary(ggplot2)\n\n# Basic 3-axis Sankey\nggplot(flow_data,\n       aes(axis1 = sex, axis2 = education, axis3 = occupation, y = n)) +\n    geom_alluvium(aes(fill = sex), width = 1/12) +\n    geom_stratum(width = 1/12, fill = \"grey80\", color = \"black\") +\n    geom_text(stat = \"stratum\", aes(label = after_stat(stratum)), size = 3) +\n    scale_x_discrete(limits = c(\"Sex\", \"Education\", \"Occupation\"), expand = c(.05, .05)) +\n    labs(title = \"Flow from Sex to Education to Occupation\",\n         y = \"Number of People\") +\n    theme_minimal()+\n    theme(legend.position = \"bottom\")\n```\n:::\n\n:::\n\n::: {.column width=\"50%\"}\n\n::: {.cell}\n::: {.cell-output-display}\n![](index_files/figure-revealjs/unnamed-chunk-20-1.png){width=480}\n:::\n:::\n\n:::\n\n## Step 3: regroup categorical data {.smaller}\n\n> Using tools like `forcats::fct_lump()` and binning to reduce the number of flows and make the diagram more readable.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nadult_sankey <- adult_sankey %>%\n    # keep the five most common occupations\n    mutate(occupation = fct_lump(occupation, n = 5)) %>%\n    # group education levels\n    mutate(education_group = case_when(\n    education %in% c(\"Preschool\", \"1st-4th\", \"5th-6th\", \"7th-8th\", \"9th\", \"10th\", \"11th\", \"12th\") ~ \"Less than HS\",\n    education == \"HS-grad\" ~ \"HS Graduate\",\n    education %in% c(\"Some-college\", \"Assoc-acdm\", \"Assoc-voc\") ~ \"Some College / Associate\",\n    education %in% c(\"Bachelors\") ~ \"Bachelor's\",\n    education %in% c(\"Masters\", \"Doctorate\", \"Prof-school\") ~ \"Grad Degree\",\n    TRUE ~ \"Other\"\n  )) %>%\n  mutate(education_group = factor(education_group, levels = c(\"Less than HS\", \"HS Graduate\", \"Some College / Associate\", \"Bachelor's\", \"Grad Degree\")))\nflow_data <- adult_sankey %>%\n  count(sex, education_group, occupation, income)\nglimpse(flow_data)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 120\nColumns: 5\n$ sex             <chr> \"Female\", \"Female\", \"Female\", \"Female\", \"Female\", \"Fem…\n$ education_group <fct> Less than HS, Less than HS, Less than HS, Less than HS…\n$ occupation      <fct> Adm-clerical, Adm-clerical, Craft-repair, Craft-repair…\n$ income          <chr> \"<=50K\", \">50K\", \"<=50K\", \">50K\", \"<=50K\", \">50K\", \"<=…\n$ n               <int> 108, 1, 29, 5, 25, 3, 20, 1, 191, 1, 925, 12, 883, 85,…\n```\n\n\n:::\n:::\n\n\n## Step 4: replot Sankey diagram {.smaller}\n\n::: {.column width=\"30%\"}\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Plot Sankey with 4 axes\nggplot(flow_data,\n       aes(axis1 = sex, axis2 = education_group, axis3 = occupation, axis4 = income, y = n)) +\n    geom_alluvium(aes(fill = sex), width = 1/12) +\n    geom_stratum(width = 1/12, fill = \"grey90\", color = \"black\") +\n    geom_text(stat = \"stratum\", aes(label = after_stat(stratum)), size = 3) +\n    scale_x_discrete(limits = c(\"Sex\", \"Education\", \"Occupation\", \"Income\"), expand = c(.05, .05)) +\n    labs(title = \"Simplified Flow: Sex → Education → Occupation → Income\",\n         y = \"Number of People\") +\n    theme_minimal() +\n    theme(legend.position = \"bottom\")\n```\n:::\n\n\n:::\n\n::: {.column width=\"70%\"}\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](index_files/figure-revealjs/unnamed-chunk-23-1.png){width=672}\n:::\n:::\n\n:::\n\n## Step 5: filter out weak links {.smaller}\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nflow_data_filtered <- flow_data %>%\n  filter(n >= 0.005 * sum(n))  # Keep flows >= 0.5% of total\n```\n:::\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](index_files/figure-revealjs/unnamed-chunk-25-1.png){width=672}\n:::\n:::\n\n## What is a Parallel Coordinates Plot (PCP)? {.smaller}\n> PCP does not show the classic Cartesian coordinate plane, but each numerical variable is given its own axis. All axes are placed **parallel**, **vertical**, and **equally spaced**.\n\n- A visualization for **multivariate data**, especially numeric.\n- Each line represents:\n  - an **individual** (for raw data), or\n  - a **group profile** (for summarized counts).\n- Useful for spotting clusters, trends, and differences between groups.\n\n## Variation 1: Individual-level PCP {.smaller}\n\n>Scaling variable is a crucial step to build a proper parallel coordinates chart. It transforms the raw data to a new scale that is common with other variables, and thus allow to compare them.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(GGally)\n# Prepare numeric individual-level data\nadult_pc <- adult %>%\n  select(age, education_num, hours_per_week, capital_gain, capital_loss, income) %>%\n  filter(complete.cases(.)) %>%\n  mutate(across(where(is.numeric), rescale))  # normalize for comparability\n\n# Sample for readability\nset.seed(123)\nadult_sample <- adult_pc %>%\n  group_by(income) %>%\n  sample_n(250)\nglimpse(adult_sample)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 500\nColumns: 6\nGroups: income [2]\n$ age            <dbl> 0.61643836, 0.38356164, 0.90410959, 0.24657534, 0.47945…\n$ education_num  <dbl> 0.5333333, 0.6000000, 0.5333333, 0.6666667, 0.6000000, …\n$ hours_per_week <dbl> 0.3979592, 0.3979592, 0.1938776, 0.2959184, 0.3979592, …\n$ capital_gain   <dbl> 0.00000000, 0.00000000, 0.00000000, 0.00000000, 0.00000…\n$ capital_loss   <dbl> 0.0000000, 0.0000000, 0.0000000, 0.0000000, 0.0000000, …\n$ income         <chr> \"<=50K\", \"<=50K\", \"<=50K\", \"<=50K\", \"<=50K\", \"<=50K\", \"…\n```\n\n\n:::\n:::\n\n\n## Variation 1: Individual-level PCP {.smaller}\n\n::: {.cell}\n\n```{.r .cell-code}\n# Individual-level parallel coordinate plot\nGGally::ggparcoord(\n  data = adult_sample,\n  columns = 1:5,\n  groupColumn = 6,\n  scale = \"globalminmax\",\n  showPoints = FALSE,\n  alphaLines = 0.3,\n  title = \"Parallel Coordinate Plot (Individual-Level)\") +\n  theme_minimal() +\n  labs(x = \"Variables\", y = \"Normalized Value\")\n```\n\n::: {.cell-output-display}\n![](index_files/figure-revealjs/unnamed-chunk-27-1.png){width=672}\n:::\n:::\n\n\n## Variation 2: Group-level PCP {.smaller}\n\n>In this variation, we summarize the data to create group profiles, which allows us to visualize the average characteristics of each income group across multiple variables.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Count and reshape for parallel coordinates\nedu_occ_income <- adult_sankey %>%\n  count(income, education_group, occupation) %>%\n  pivot_wider(names_from = occupation, values_from = n, values_fill = 0)%>%\n  mutate(income = factor(income, labels = c(\"<=50K\", \">50K\")))\nglimpse(edu_occ_income)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 10\nColumns: 8\n$ income            <fct> <=50K, <=50K, <=50K, <=50K, <=50K, >50K, >50K, >50K,…\n$ education_group   <fct> Less than HS, HS Graduate, Some College / Associate,…\n$ `Adm-clerical`    <int> 170, 1202, 1451, 387, 53, 6, 163, 190, 119, 29\n$ `Craft-repair`    <int> 619, 1517, 881, 138, 15, 66, 405, 354, 88, 16\n$ `Exec-managerial` <int> 82, 546, 732, 590, 148, 26, 261, 442, 779, 460\n$ `Prof-specialty`  <int> 50, 173, 525, 916, 617, 7, 60, 213, 579, 1000\n$ Sales             <int> 328, 869, 979, 427, 64, 25, 200, 280, 382, 96\n$ Other             <int> 2760, 4519, 3159, 676, 127, 114, 586, 534, 274, 87\n```\n\n\n:::\n:::\n\n\n## Variation 2: Group-level PCP {.smaller}\n\n::: {.column width=\"50%\"}\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Group-level profile parallel coordinate plot\nincome_labels <- c(`1` = \"Income <=50K\", `2` = \"Income >50K\")\nGGally::ggparcoord(\n    data = edu_occ_income,\n    columns = 3:ncol(edu_occ_income), # occupation columns\n    groupColumn = 2, #education group\n    scale = \"globalminmax\",\n    showPoints = TRUE,\n    title = \"Group Profile Plot:\\nEducation vs. Occupation by Income\") +\n    theme_minimal(base_size = 14) +\n    facet_wrap(. ~ income, ncol = 1, labeller = as_labeller(income_labels), scales = \"free\") +\n    labs(x = \"Occupation\", y = \"Relative Count\") +\n    coord_flip() +\n    theme(legend.position = \"bottom\")+\n    guides(color = guide_legend(nrow = 3)) \n```\n:::\n\n:::\n\n\n::: {.column width=\"50%\"}\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](index_files/figure-revealjs/unnamed-chunk-30-1.png){width=672}\n:::\n:::\n\n:::\n\n## Comparing two variations {.smaller}\n\n::: {.column width=\"50%\"}\n\nIndividual-level parallel coordinates plot:\n\n- Each line = one person\n- Color by group variable, `income`\n- Use this to explore variable interactions and clusters\n\n:::\n\n::: {.column width=\"50%\"}\n\nGroup-level parallel coordinates plot:\n\n- Each line = one education group\n- Use this to compare how different `education` groups are distributed across `occupations`\n- `income` in represented by facets\n:::\n\n. . .\n\n\n##  {background=\"#033C5A\"}\n<br>\n<br>\n<br>\n\n<div class=\"page-center vertical-center\">\n<p class=\"custom-subtitle bottombr\">{{<fa tools title=\"let's practice\" >}} Your turn to make some graphs! </p>\n<p class=\"caption-text\">*~ Head over to lab3 notebook! ~*</p>\n</div>\n\n\n## Outline for today {.smaller}\n\n- Introducing the datasets\n\n- Review faceted plots\n\n- Introduce radar charts, Sankey diagrams, and parallel coordinates plot\n\n- **Dos and Don'ts when designing visualizations**\n\n## DO: Clear, informative titles and labels {.smaller-title}\n\n:::{.column width=\"50%\"}\n✅ DO\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(mtcars, aes(x = factor(cyl), y = mpg)) +\n  geom_boxplot() +\n  labs(\n    title = \"Miles per Gallon by Number of Cylinders\",\n    x = \"Number of Cylinders\",\n    y = \"MPG\"\n  ) +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](index_files/figure-revealjs/unnamed-chunk-31-1.png){width=480}\n:::\n:::\n\n\n:::\n\n:::{.column width=\"50%\"}\n❌ Don’t\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(mtcars, aes(x = factor(cyl), y = mpg)) +\n  geom_boxplot() +\n  ggtitle(\"Plot 1\") +  # Uninformative\n  theme_gray()         # Cluttered default theme\n```\n\n::: {.cell-output-display}\n![](index_files/figure-revealjs/unnamed-chunk-32-1.png){width=480}\n:::\n:::\n\n\n:::\n\n## DO: Choose the right chart type {.smaller-title}\n\n:::{.column width=\"50%\"}\n✅ DO\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(airquality, aes(x = Day, y = Temp)) +\n  geom_line() +\n  facet_wrap(~ Month) +\n  labs(title = \"Daily Temperature by Month\", x = \"Day\", y = \"Temperature (F)\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](index_files/figure-revealjs/unnamed-chunk-33-1.png){width=480}\n:::\n:::\n\n\n:::\n\n:::{.column width=\"50%\"}\n❌ Don’t\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(airquality, aes(x = Month, y = Temp)) +\n  geom_bar(stat = \"identity\") +\n  ggtitle(\"Temp by Month\")  # Misleading chart type\n```\n\n::: {.cell-output-display}\n![](index_files/figure-revealjs/unnamed-chunk-34-1.png){width=480}\n:::\n:::\n\n\n*What is this chart showing? Average temperature or total temperature by month?*\n\n:::\n\n## DO: Choose the right chart type {.smaller-title}\n\n:::{.column width=\"50%\"}\n✅ DO\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(airquality, aes(x = Day, y = Temp)) +\n  geom_line() +\n  facet_wrap(~ Month) +\n  labs(title = \"Daily Temperature by Month\", x = \"Day\", y = \"Temperature (F)\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](index_files/figure-revealjs/unnamed-chunk-35-1.png){width=480}\n:::\n:::\n\n\n:::\n\n:::{.column width=\"50%\"}\n❌ Don’t\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(airquality, aes(x = Month, y = Temp)) +\n  geom_bar(stat = \"identity\", color = 'orange') +\n  ggtitle(\"Temp by Month\")  # Misleading chart type\n```\n\n::: {.cell-output-display}\n![](index_files/figure-revealjs/unnamed-chunk-36-1.png){width=480}\n:::\n:::\n\n\n*It stacks daily temperature on top of each other, which makes no sense*\n\n:::\n\n## DO: Use accessible colors {.smaller-title}\n\n:::{.column width=\"50%\"}\n✅ DO use `viridis` scale\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(mtcars, aes(x = wt, y = mpg, color = hp)) +\n  geom_point(size = 3) +\n  scale_color_viridis_c(option = \"plasma\") +\n  labs(\n    title = \"Fuel Efficiency vs Weight of Car\",\n    x = \"Weight (1000 lbs)\",\n    y = \"Miles per Gallon\",\n    color = \"Horsepower\"\n  ) +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](index_files/figure-revealjs/unnamed-chunk-37-1.png){width=480}\n:::\n:::\n\n\n:::\n\n:::{.column width=\"50%\"}\n❌ Don’t use rainbow colors\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(mtcars, aes(x = wt, y = mpg, color = hp)) +\n  geom_point(size = 3) +\n  scale_color_gradientn(colors = rainbow(7)) +\n  labs(\n    title = \"Fuel Efficiency vs Weight of Car\",\n    x = \"Weight (1000 lbs)\",\n    y = \"Miles per Gallon\",\n    color = \"Horsepower\"\n  ) +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](index_files/figure-revealjs/unnamed-chunk-38-1.png){width=480}\n:::\n:::\n\n\n:::\n\n\n## DO: Order categorical axes intentionally {.smaller-title}\n\n:::{.column width=\"50%\"}\n✅ DO \n\n\n::: {.cell}\n\n```{.r .cell-code}\nmtcars %>%\n    rownames_to_column(var = \"model\") %>%\n    ggplot(aes(x = fct_reorder(model, mpg), y = mpg)) +\n    geom_col(fill = \"steelblue\") +\n    labs(title = \"Fuel Efficiency by Car Model\", x = \"Car Model (ordered by MPG)\", y = \"Miles per Gallon\") +\n    coord_flip() +\n    theme_minimal()\n```\n\n::: {.cell-output-display}\n![](index_files/figure-revealjs/unnamed-chunk-39-1.png){width=480}\n:::\n:::\n\n\n:::\n\n:::{.column width=\"50%\"}\n❌ Don’t \n\n\n::: {.cell}\n\n```{.r .cell-code}\nmtcars %>%\n    rownames_to_column(var = \"model\") %>%\n    ggplot(aes(x = model, y = mpg)) +\n    geom_col(fill = \"steelblue\") +\n    labs(title = \"Fuel Efficiency by Car Model\", x = \"Car Model (ordered by MPG)\", y = \"Miles per Gallon\") +\n    coord_flip() +\n    theme_minimal()\n```\n\n::: {.cell-output-display}\n![](index_files/figure-revealjs/unnamed-chunk-40-1.png){width=480}\n:::\n:::\n\n\n:::\n\n## DO: Use appropriate scales {.smaller-title}\n\n:::{.column width=\"50%\"}\n✅ DO log-transform right skewed variables\n\n\n::: {.cell}\n\n```{.r .cell-code  code-line-numbers=\"3,4\"}\nggplot(diamonds, aes(x = carat, y = price)) +\n  geom_point(alpha = 0.2, color = \"steelblue\") +\n  scale_x_log10() +\n  scale_y_log10(labels = scales::dollar_format(accuracy = 1)) +\n  labs(\n    title = \"Diamond Price vs Carat (Log-Log Scale)\",\n    x = \"Carat (log scale)\",\n    y = \"Price (log scale)\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](index_files/figure-revealjs/unnamed-chunk-41-1.png){width=480}\n:::\n:::\n\n\n:::\n\n:::{.column width=\"50%\"}\n❌ Don’t mindlessly use raw scale\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(diamonds, aes(x = carat, y = price)) +\n  geom_point(alpha = 0.2, color = \"steelblue\") +\n  labs(\n    title = \"Diamond Price vs Carat (Raw Scale)\",\n    x = \"Carat\",\n    y = \"Price\"\n  ) +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](index_files/figure-revealjs/unnamed-chunk-42-1.png){width=480}\n:::\n:::\n\n\n:::\n\n## DO: Add helpful annotations {.smaller-title}\n\n:::{.column width=\"50%\"}\n✅ DO use direct labels\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlabel_df <- mtcars %>%\n  group_by(cyl) %>%\n  summarise(hp = mean(hp), mpg = mean(mpg))\nggplot(mtcars, aes(x = hp, y = mpg, color = factor(cyl))) +\n  geom_point(size = 3, alpha = 0.6) +\n  ggrepel::geom_label_repel(\n    data = label_df,\n    aes(label = paste0(cyl, \" cyl\"), fill = factor(cyl)),\n    show.legend = FALSE, size = 4, fontface = \"bold\", color = \"black\") +\n  labs(title = \"Fuel Efficiency vs Horsepower\", x = \"Horsepower\", y = \"Miles per Gallon\") +\n    guides(color = \"none\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](index_files/figure-revealjs/unnamed-chunk-43-1.png){width=480}\n:::\n:::\n\n\n:::\n\n:::{.column width=\"50%\"}\n❌ Don’t only rely on legends\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(mtcars, aes(x = hp, y = mpg, color = factor(cyl))) +\n  geom_point(size = 3) +\n  labs(\n    title = \"Fuel Efficiency vs Horsepower\",\n    x = \"Horsepower\",\n    y = \"Miles per Gallon\",\n    color = \"Cylinders\"\n  ) +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](index_files/figure-revealjs/unnamed-chunk-44-1.png){width=480}\n:::\n:::\n\n\n:::\n\n## DO: Use clear typeface and fonts {.smaller-title}\n\n:::{.column width=\"50%\"}\n✅ DO \n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(showtext)\nfont_add_google(\"Lato\", \"lato\")\nshowtext_auto()\nggplot(mtcars, aes(x = factor(cyl), y = mpg)) +\n  geom_boxplot() +\n  theme_minimal(base_family = \"lato\") +\n  labs(title = \"MPG by Cylinders (Lato Font)\")\n```\n\n::: {.cell-output-display}\n![](index_files/figure-revealjs/unnamed-chunk-45-1.png){width=480}\n:::\n:::\n\n\n:::\n\n:::{.column width=\"50%\"}\n❌ Don’t have tiny fonts\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(mtcars, aes(x = factor(cyl), y = mpg)) +\n  geom_boxplot() +\n  theme(text = element_text(size = 8)) +\n  labs(title = \"MPG by Cylinders\")\n```\n\n::: {.cell-output-display}\n![](index_files/figure-revealjs/unnamed-chunk-46-1.png){width=960}\n:::\n:::\n\n\n:::\n\n## More on typeface {.smaller}\n\n![](images/typeface-matters.png)\n\n::: citation\nSource: Typography for a better user experience, by [Suvo Ray](https://www.suvoray.com/notes/typography-for-a-better-user-experience)\n:::\n\n## Some general rules {.smaller}\n\n- Use **sans-serif** fonts for digital displays (e.g., Arial, Helvetica, Lato).\n- **Serif** fonts are typically only used for visualization headlines (e.g., Times New Roman, Georgia).\n- Avoid using too many typefaces (just 1-3)\n- Use a typeface with lining figures for numerals\n![](images/font-1.png){ width=\"50%\"}\n- Use a monospaced typeface for numerals\n![](images/font-2.png){ width=\"50%\"}\n\n\n## Create hierarchy with font size, weight, and style {.smaller-title}\n![](images/font-3.png)\n\n::: citation\nSource: The UX Designer's Guide to Typography by [Chaosamran_Studio](https://www.interaction-design.org/literature/article/the-ux-designer-s-guide-to-typography)\n:::\n\n## Pick a typeface from Google Fonts {.smaller}\n\n![](images/google-fonts.gif)\n\n::: citation\n[https://fonts.google.com/](https://fonts.google.com/)\n\nSource: [EDS 240](https://eds-240-data-viz.github.io/course-materials/lecture-slides/lecture6.1-typography-slides.html#/pick-google-fonts)\n:::\n\n\n##  End-of-Class Survey {background=\"#033C5A\"}\n<br>\n<br>\n<br>\n\n<div class=\"page-center vertical-center\">\n<p class=\"custom-subtitle bottombr\">{{<fa pen-to-square title=\"edit or fill out survey\">}} Fill out the end-of-class survey </p>\n<p class=\"caption-text\">*~ This is the end of Lab 3 ~*</p>\n</div>\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n```{=html}\n<countdown-timer class=\"countdown\" id=\"timer_951d40e3\" minutes=\"10\" seconds=\"0\" update-every=\"1\" play-sound=\"true\" tabindex=\"0\" style=\"right:0;bottom:0;--countdown-font-size:2em;--countdown-color-border:#FFFFFF;--countdown-color-text:#7aa81e;--countdown-color-running-background:#7aa81e;--countdown-color-running-text:#FFFFFF;--countdown-color-finished-background:#ffa07a;--countdown-color-finished-text:#FFFFFF;\"></countdown-timer>\n```\n\n:::\n:::\n\n",
    "supporting": [
      "index_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<link href=\"../../site_libs/countdown-0.6.0/countdown.css\" rel=\"stylesheet\" />\n<script src=\"../../site_libs/countdown-0.6.0/countdown.js\"></script>\n"
      ],
      "include-after-body": [
        "\n<script>\n  // htmlwidgets need to know to resize themselves when slides are shown/hidden.\n  // Fire the \"slideenter\" event (handled by htmlwidgets.js) when the current\n  // slide changes (different for each slide format).\n  (function () {\n    // dispatch for htmlwidgets\n    function fireSlideEnter() {\n      const event = window.document.createEvent(\"Event\");\n      event.initEvent(\"slideenter\", true, true);\n      window.document.dispatchEvent(event);\n    }\n\n    function fireSlideChanged(previousSlide, currentSlide) {\n      fireSlideEnter();\n\n      // dispatch for shiny\n      if (window.jQuery) {\n        if (previousSlide) {\n          window.jQuery(previousSlide).trigger(\"hidden\");\n        }\n        if (currentSlide) {\n          window.jQuery(currentSlide).trigger(\"shown\");\n        }\n      }\n    }\n\n    // hookup for slidy\n    if (window.w3c_slidy) {\n      window.w3c_slidy.add_observer(function (slide_num) {\n        // slide_num starts at position 1\n        fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);\n      });\n    }\n\n  })();\n</script>\n\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}